<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.fooddelivery</groupId>
  <artifactId>food-delivery-backend</artifactId>
  <version>1.0.0-SNAPSHOT</version>
  <packaging>pom</packaging>
  <name>Food Delivery Backend</name>
  <modules>
    <module>food-delivery-backend/discovery-server</module>
    <module>food-delivery-backend/api-gateway</module>
    <module>food-delivery-backend/auth-service</module>
    <module>food-delivery-backend/restaurant-service</module>
    <module>food-delivery-backend/order-service</module>
  </modules>
</project>