server: { port: 8082 }
spring:
  application: { name: restaurant-service }
  datasource: { url: jdbc:postgresql://localhost:5432/fooddelivery, username: fooddelivery, password: fooddelivery }
  jpa: { hibernate: { ddl-auto: update }, open-in-view: false }
eureka:
  client:
    service-url: { defaultZone: http://localhost:8761/eureka/ }
